/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.grid.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AnomalyEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1483902001897607974L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AnomalyEvent\",\"namespace\":\"com.grid.events\",\"fields\":[{\"name\":\"anomaly_type\",\"type\":\"string\"},{\"name\":\"severity\",\"type\":{\"type\":\"enum\",\"name\":\"SeverityLevel\",\"symbols\":[\"INFO\",\"WARNING\",\"ERROR\",\"CRITICAL\"]}},{\"name\":\"original_event\",\"type\":{\"type\":\"record\",\"name\":\"SensorReading\",\"fields\":[{\"name\":\"meter_id\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"voltage\",\"type\":\"double\"},{\"name\":\"current\",\"type\":\"double\"},{\"name\":\"temperature\",\"type\":\"double\"},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"threshold_used\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"deviation\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<AnomalyEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AnomalyEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AnomalyEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AnomalyEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AnomalyEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AnomalyEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AnomalyEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AnomalyEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AnomalyEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence anomaly_type;
  private com.grid.events.SeverityLevel severity;
  private com.grid.events.SensorReading original_event;
  private java.lang.Double threshold_used;
  private java.lang.Double deviation;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AnomalyEvent() {}

  /**
   * All-args constructor.
   * @param anomaly_type The new value for anomaly_type
   * @param severity The new value for severity
   * @param original_event The new value for original_event
   * @param threshold_used The new value for threshold_used
   * @param deviation The new value for deviation
   */
  public AnomalyEvent(java.lang.CharSequence anomaly_type, com.grid.events.SeverityLevel severity, com.grid.events.SensorReading original_event, java.lang.Double threshold_used, java.lang.Double deviation) {
    this.anomaly_type = anomaly_type;
    this.severity = severity;
    this.original_event = original_event;
    this.threshold_used = threshold_used;
    this.deviation = deviation;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return anomaly_type;
    case 1: return severity;
    case 2: return original_event;
    case 3: return threshold_used;
    case 4: return deviation;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: anomaly_type = (java.lang.CharSequence)value$; break;
    case 1: severity = (com.grid.events.SeverityLevel)value$; break;
    case 2: original_event = (com.grid.events.SensorReading)value$; break;
    case 3: threshold_used = (java.lang.Double)value$; break;
    case 4: deviation = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'anomaly_type' field.
   * @return The value of the 'anomaly_type' field.
   */
  public java.lang.CharSequence getAnomalyType() {
    return anomaly_type;
  }


  /**
   * Sets the value of the 'anomaly_type' field.
   * @param value the value to set.
   */
  public void setAnomalyType(java.lang.CharSequence value) {
    this.anomaly_type = value;
  }

  /**
   * Gets the value of the 'severity' field.
   * @return The value of the 'severity' field.
   */
  public com.grid.events.SeverityLevel getSeverity() {
    return severity;
  }


  /**
   * Sets the value of the 'severity' field.
   * @param value the value to set.
   */
  public void setSeverity(com.grid.events.SeverityLevel value) {
    this.severity = value;
  }

  /**
   * Gets the value of the 'original_event' field.
   * @return The value of the 'original_event' field.
   */
  public com.grid.events.SensorReading getOriginalEvent() {
    return original_event;
  }


  /**
   * Sets the value of the 'original_event' field.
   * @param value the value to set.
   */
  public void setOriginalEvent(com.grid.events.SensorReading value) {
    this.original_event = value;
  }

  /**
   * Gets the value of the 'threshold_used' field.
   * @return The value of the 'threshold_used' field.
   */
  public java.lang.Double getThresholdUsed() {
    return threshold_used;
  }


  /**
   * Sets the value of the 'threshold_used' field.
   * @param value the value to set.
   */
  public void setThresholdUsed(java.lang.Double value) {
    this.threshold_used = value;
  }

  /**
   * Gets the value of the 'deviation' field.
   * @return The value of the 'deviation' field.
   */
  public java.lang.Double getDeviation() {
    return deviation;
  }


  /**
   * Sets the value of the 'deviation' field.
   * @param value the value to set.
   */
  public void setDeviation(java.lang.Double value) {
    this.deviation = value;
  }

  /**
   * Creates a new AnomalyEvent RecordBuilder.
   * @return A new AnomalyEvent RecordBuilder
   */
  public static com.grid.events.AnomalyEvent.Builder newBuilder() {
    return new com.grid.events.AnomalyEvent.Builder();
  }

  /**
   * Creates a new AnomalyEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AnomalyEvent RecordBuilder
   */
  public static com.grid.events.AnomalyEvent.Builder newBuilder(com.grid.events.AnomalyEvent.Builder other) {
    if (other == null) {
      return new com.grid.events.AnomalyEvent.Builder();
    } else {
      return new com.grid.events.AnomalyEvent.Builder(other);
    }
  }

  /**
   * Creates a new AnomalyEvent RecordBuilder by copying an existing AnomalyEvent instance.
   * @param other The existing instance to copy.
   * @return A new AnomalyEvent RecordBuilder
   */
  public static com.grid.events.AnomalyEvent.Builder newBuilder(com.grid.events.AnomalyEvent other) {
    if (other == null) {
      return new com.grid.events.AnomalyEvent.Builder();
    } else {
      return new com.grid.events.AnomalyEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AnomalyEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AnomalyEvent>
    implements org.apache.avro.data.RecordBuilder<AnomalyEvent> {

    private java.lang.CharSequence anomaly_type;
    private com.grid.events.SeverityLevel severity;
    private com.grid.events.SensorReading original_event;
    private com.grid.events.SensorReading.Builder original_eventBuilder;
    private java.lang.Double threshold_used;
    private java.lang.Double deviation;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.grid.events.AnomalyEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.anomaly_type)) {
        this.anomaly_type = data().deepCopy(fields()[0].schema(), other.anomaly_type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.severity)) {
        this.severity = data().deepCopy(fields()[1].schema(), other.severity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.original_event)) {
        this.original_event = data().deepCopy(fields()[2].schema(), other.original_event);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasOriginalEventBuilder()) {
        this.original_eventBuilder = com.grid.events.SensorReading.newBuilder(other.getOriginalEventBuilder());
      }
      if (isValidValue(fields()[3], other.threshold_used)) {
        this.threshold_used = data().deepCopy(fields()[3].schema(), other.threshold_used);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.deviation)) {
        this.deviation = data().deepCopy(fields()[4].schema(), other.deviation);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing AnomalyEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.grid.events.AnomalyEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.anomaly_type)) {
        this.anomaly_type = data().deepCopy(fields()[0].schema(), other.anomaly_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.severity)) {
        this.severity = data().deepCopy(fields()[1].schema(), other.severity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.original_event)) {
        this.original_event = data().deepCopy(fields()[2].schema(), other.original_event);
        fieldSetFlags()[2] = true;
      }
      this.original_eventBuilder = null;
      if (isValidValue(fields()[3], other.threshold_used)) {
        this.threshold_used = data().deepCopy(fields()[3].schema(), other.threshold_used);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.deviation)) {
        this.deviation = data().deepCopy(fields()[4].schema(), other.deviation);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'anomaly_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getAnomalyType() {
      return anomaly_type;
    }


    /**
      * Sets the value of the 'anomaly_type' field.
      * @param value The value of 'anomaly_type'.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder setAnomalyType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.anomaly_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'anomaly_type' field has been set.
      * @return True if the 'anomaly_type' field has been set, false otherwise.
      */
    public boolean hasAnomalyType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'anomaly_type' field.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder clearAnomalyType() {
      anomaly_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'severity' field.
      * @return The value.
      */
    public com.grid.events.SeverityLevel getSeverity() {
      return severity;
    }


    /**
      * Sets the value of the 'severity' field.
      * @param value The value of 'severity'.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder setSeverity(com.grid.events.SeverityLevel value) {
      validate(fields()[1], value);
      this.severity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'severity' field has been set.
      * @return True if the 'severity' field has been set, false otherwise.
      */
    public boolean hasSeverity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'severity' field.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder clearSeverity() {
      severity = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'original_event' field.
      * @return The value.
      */
    public com.grid.events.SensorReading getOriginalEvent() {
      return original_event;
    }


    /**
      * Sets the value of the 'original_event' field.
      * @param value The value of 'original_event'.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder setOriginalEvent(com.grid.events.SensorReading value) {
      validate(fields()[2], value);
      this.original_eventBuilder = null;
      this.original_event = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'original_event' field has been set.
      * @return True if the 'original_event' field has been set, false otherwise.
      */
    public boolean hasOriginalEvent() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'original_event' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.grid.events.SensorReading.Builder getOriginalEventBuilder() {
      if (original_eventBuilder == null) {
        if (hasOriginalEvent()) {
          setOriginalEventBuilder(com.grid.events.SensorReading.newBuilder(original_event));
        } else {
          setOriginalEventBuilder(com.grid.events.SensorReading.newBuilder());
        }
      }
      return original_eventBuilder;
    }

    /**
     * Sets the Builder instance for the 'original_event' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.grid.events.AnomalyEvent.Builder setOriginalEventBuilder(com.grid.events.SensorReading.Builder value) {
      clearOriginalEvent();
      original_eventBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'original_event' field has an active Builder instance
     * @return True if the 'original_event' field has an active Builder instance
     */
    public boolean hasOriginalEventBuilder() {
      return original_eventBuilder != null;
    }

    /**
      * Clears the value of the 'original_event' field.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder clearOriginalEvent() {
      original_event = null;
      original_eventBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'threshold_used' field.
      * @return The value.
      */
    public java.lang.Double getThresholdUsed() {
      return threshold_used;
    }


    /**
      * Sets the value of the 'threshold_used' field.
      * @param value The value of 'threshold_used'.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder setThresholdUsed(java.lang.Double value) {
      validate(fields()[3], value);
      this.threshold_used = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'threshold_used' field has been set.
      * @return True if the 'threshold_used' field has been set, false otherwise.
      */
    public boolean hasThresholdUsed() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'threshold_used' field.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder clearThresholdUsed() {
      threshold_used = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviation' field.
      * @return The value.
      */
    public java.lang.Double getDeviation() {
      return deviation;
    }


    /**
      * Sets the value of the 'deviation' field.
      * @param value The value of 'deviation'.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder setDeviation(java.lang.Double value) {
      validate(fields()[4], value);
      this.deviation = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'deviation' field has been set.
      * @return True if the 'deviation' field has been set, false otherwise.
      */
    public boolean hasDeviation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'deviation' field.
      * @return This builder.
      */
    public com.grid.events.AnomalyEvent.Builder clearDeviation() {
      deviation = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AnomalyEvent build() {
      try {
        AnomalyEvent record = new AnomalyEvent();
        record.anomaly_type = fieldSetFlags()[0] ? this.anomaly_type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.severity = fieldSetFlags()[1] ? this.severity : (com.grid.events.SeverityLevel) defaultValue(fields()[1]);
        if (original_eventBuilder != null) {
          try {
            record.original_event = this.original_eventBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("original_event"));
            throw e;
          }
        } else {
          record.original_event = fieldSetFlags()[2] ? this.original_event : (com.grid.events.SensorReading) defaultValue(fields()[2]);
        }
        record.threshold_used = fieldSetFlags()[3] ? this.threshold_used : (java.lang.Double) defaultValue(fields()[3]);
        record.deviation = fieldSetFlags()[4] ? this.deviation : (java.lang.Double) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AnomalyEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AnomalyEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AnomalyEvent>
    READER$ = (org.apache.avro.io.DatumReader<AnomalyEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










