/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.grid.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SensorReading extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2572130332816639826L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorReading\",\"namespace\":\"com.grid.events\",\"fields\":[{\"name\":\"meter_id\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"voltage\",\"type\":\"double\"},{\"name\":\"current\",\"type\":\"double\"},{\"name\":\"temperature\",\"type\":\"double\"},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<SensorReading> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SensorReading> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SensorReading> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SensorReading> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SensorReading> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SensorReading to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SensorReading from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SensorReading instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SensorReading fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence meter_id;
  private java.time.Instant timestamp;
  private double voltage;
  private double current;
  private double temperature;
  private java.lang.CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensorReading() {}

  /**
   * All-args constructor.
   * @param meter_id The new value for meter_id
   * @param timestamp The new value for timestamp
   * @param voltage The new value for voltage
   * @param current The new value for current
   * @param temperature The new value for temperature
   * @param status The new value for status
   */
  public SensorReading(java.lang.CharSequence meter_id, java.time.Instant timestamp, java.lang.Double voltage, java.lang.Double current, java.lang.Double temperature, java.lang.CharSequence status) {
    this.meter_id = meter_id;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.voltage = voltage;
    this.current = current;
    this.temperature = temperature;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return meter_id;
    case 1: return timestamp;
    case 2: return voltage;
    case 3: return current;
    case 4: return temperature;
    case 5: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: meter_id = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.time.Instant)value$; break;
    case 2: voltage = (java.lang.Double)value$; break;
    case 3: current = (java.lang.Double)value$; break;
    case 4: temperature = (java.lang.Double)value$; break;
    case 5: status = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'meter_id' field.
   * @return The value of the 'meter_id' field.
   */
  public java.lang.CharSequence getMeterId() {
    return meter_id;
  }


  /**
   * Sets the value of the 'meter_id' field.
   * @param value the value to set.
   */
  public void setMeterId(java.lang.CharSequence value) {
    this.meter_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'voltage' field.
   * @return The value of the 'voltage' field.
   */
  public double getVoltage() {
    return voltage;
  }


  /**
   * Sets the value of the 'voltage' field.
   * @param value the value to set.
   */
  public void setVoltage(double value) {
    this.voltage = value;
  }

  /**
   * Gets the value of the 'current' field.
   * @return The value of the 'current' field.
   */
  public double getCurrent() {
    return current;
  }


  /**
   * Sets the value of the 'current' field.
   * @param value the value to set.
   */
  public void setCurrent(double value) {
    this.current = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return The value of the 'temperature' field.
   */
  public double getTemperature() {
    return temperature;
  }


  /**
   * Sets the value of the 'temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(double value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new SensorReading RecordBuilder.
   * @return A new SensorReading RecordBuilder
   */
  public static com.grid.events.SensorReading.Builder newBuilder() {
    return new com.grid.events.SensorReading.Builder();
  }

  /**
   * Creates a new SensorReading RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensorReading RecordBuilder
   */
  public static com.grid.events.SensorReading.Builder newBuilder(com.grid.events.SensorReading.Builder other) {
    if (other == null) {
      return new com.grid.events.SensorReading.Builder();
    } else {
      return new com.grid.events.SensorReading.Builder(other);
    }
  }

  /**
   * Creates a new SensorReading RecordBuilder by copying an existing SensorReading instance.
   * @param other The existing instance to copy.
   * @return A new SensorReading RecordBuilder
   */
  public static com.grid.events.SensorReading.Builder newBuilder(com.grid.events.SensorReading other) {
    if (other == null) {
      return new com.grid.events.SensorReading.Builder();
    } else {
      return new com.grid.events.SensorReading.Builder(other);
    }
  }

  /**
   * RecordBuilder for SensorReading instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorReading>
    implements org.apache.avro.data.RecordBuilder<SensorReading> {

    private java.lang.CharSequence meter_id;
    private java.time.Instant timestamp;
    private double voltage;
    private double current;
    private double temperature;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.grid.events.SensorReading.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.meter_id)) {
        this.meter_id = data().deepCopy(fields()[0].schema(), other.meter_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.voltage)) {
        this.voltage = data().deepCopy(fields()[2].schema(), other.voltage);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.current)) {
        this.current = data().deepCopy(fields()[3].schema(), other.current);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.temperature)) {
        this.temperature = data().deepCopy(fields()[4].schema(), other.temperature);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing SensorReading instance
     * @param other The existing instance to copy.
     */
    private Builder(com.grid.events.SensorReading other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.meter_id)) {
        this.meter_id = data().deepCopy(fields()[0].schema(), other.meter_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.voltage)) {
        this.voltage = data().deepCopy(fields()[2].schema(), other.voltage);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.current)) {
        this.current = data().deepCopy(fields()[3].schema(), other.current);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.temperature)) {
        this.temperature = data().deepCopy(fields()[4].schema(), other.temperature);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'meter_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getMeterId() {
      return meter_id;
    }


    /**
      * Sets the value of the 'meter_id' field.
      * @param value The value of 'meter_id'.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder setMeterId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.meter_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'meter_id' field has been set.
      * @return True if the 'meter_id' field has been set, false otherwise.
      */
    public boolean hasMeterId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'meter_id' field.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder clearMeterId() {
      meter_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[1], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'voltage' field.
      * @return The value.
      */
    public double getVoltage() {
      return voltage;
    }


    /**
      * Sets the value of the 'voltage' field.
      * @param value The value of 'voltage'.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder setVoltage(double value) {
      validate(fields()[2], value);
      this.voltage = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'voltage' field has been set.
      * @return True if the 'voltage' field has been set, false otherwise.
      */
    public boolean hasVoltage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'voltage' field.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder clearVoltage() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'current' field.
      * @return The value.
      */
    public double getCurrent() {
      return current;
    }


    /**
      * Sets the value of the 'current' field.
      * @param value The value of 'current'.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder setCurrent(double value) {
      validate(fields()[3], value);
      this.current = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'current' field has been set.
      * @return True if the 'current' field has been set, false otherwise.
      */
    public boolean hasCurrent() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'current' field.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder clearCurrent() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature' field.
      * @return The value.
      */
    public double getTemperature() {
      return temperature;
    }


    /**
      * Sets the value of the 'temperature' field.
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder setTemperature(double value) {
      validate(fields()[4], value);
      this.temperature = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'temperature' field.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder clearTemperature() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.grid.events.SensorReading.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SensorReading build() {
      try {
        SensorReading record = new SensorReading();
        record.meter_id = fieldSetFlags()[0] ? this.meter_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.time.Instant) defaultValue(fields()[1]);
        record.voltage = fieldSetFlags()[2] ? this.voltage : (java.lang.Double) defaultValue(fields()[2]);
        record.current = fieldSetFlags()[3] ? this.current : (java.lang.Double) defaultValue(fields()[3]);
        record.temperature = fieldSetFlags()[4] ? this.temperature : (java.lang.Double) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SensorReading>
    WRITER$ = (org.apache.avro.io.DatumWriter<SensorReading>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SensorReading>
    READER$ = (org.apache.avro.io.DatumReader<SensorReading>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










