/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.grid.events;
@org.apache.avro.specific.AvroGenerated
public enum SeverityLevel implements org.apache.avro.generic.GenericEnumSymbol<SeverityLevel> {
  INFO, WARNING, ERROR, CRITICAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SeverityLevel\",\"namespace\":\"com.grid.events\",\"symbols\":[\"INFO\",\"WARNING\",\"ERROR\",\"CRITICAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
